version: '2.0'
services:
  zookeeper:
    build: zookeeper_docker
    ports: 
      - "2181:2181"
    environment:
      ZOO_PORT: 12181
  kafka:
    build: kafka_docker
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      ZOOKEEPER_CONNECT: zookeeper:2181
    links:
      - zookeeper
  producer:
    build: producer_docker
  consumer: 
    build: consumer_docker